name: 'Hello World'

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: exitcode
      run: ${{ github.action_path }}/goodbye.sh
      shell: bash
