name: Dispatch CI

on:
  workflow_dispatch:
    inputs:
      myorg:
        description: "Org name"
        default: "myorg"
      myapp:
        description: "App name"
        default: "myapp"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ format('{0}-{1}-{2}', inputs.myorg, 'stage', inputs.myapp) }}
