name: Test CI

on:
  workflow_dispatch:
    inputs:
      s3-bucket-name:
        description: "Bucket name"
        default: "myapp"
      var1:
        description: "Variable 1"
        required: true
        default: 'bitso-stage-${{ inputs.s3-bucket-name }}' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.var1 }}
