name: Matrix tests

on: 
  workflow_dispatch:
    inputs:
      cfids:
        description: "include array"
        default: '[{"environment": "sandbox", "cloudfront-id": "xxxxxxxxxx"}]'

jobs:
  build-matrix:
    name: build-matrix
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.get-envs.outputs.environments }}
      cloudfront-ids: ${{ steps.cloudfront-ids-env.outputs.cloudfront-ids }}
    steps:
      - name: Ennvironment
        id: get-envs
        run: |
          JSON=$(echo '[{"environment": "sandbox", "parm1": "aaaaa"}, {"environment": "prod", "param1": "bbbbbb"}]')
          echo "environments=$JSON"
          echo "environments=$JSON" >> $GITHUB_OUTPUT
      - name: Concat Cloudfront ids
        id: cloudfront-ids-env
        run: |
          JSON=$(echo '[{"environment": "sandbox", "parm1": "aaaaa"}, {"environment": "prod", "param1": "bbbbbb"}]' '${{ inputs.cfids }}' | jq -c -s '[ add | group_by(.environment)[] | select(length > 1) | add ]' )
          echo "cloudfront-ids=$JSON"
          echo "cloudfront-ids=$JSON" >> $GITHUB_OUTPUT

  check-matrix:
    name: check-matrix
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix: 
        environments: ${{ fromJson(needs.build-matrix.outputs.environments) }}
        includes: ${{ fromJson(needs.build-matrix.outputs.cloudfront-ids) }}
    steps:
      - name: Check 1 ${{ matrix.environment}} ${{ matrix.cloudfront-id }}
        run: |
          matrix='${{ needs.build-matrix.outputs.environments }}'
          echo $matrix
          echo $matrix | jq .

      - name: Check 2 ${{ matrix.environment }} ${{ matrix.cloudfront-id }}
        run: |
          matrix='${{ needs.build-matrix.outputs.cloudfront-ids }}'
          echo $matrix
          echo $matrix | jq .