name: Matrix tests

on: 
  workflow_dispatch:
    inputs:
      cfids:
        description: "include array"
        default: '[{"environment": "sandbox", "cloudfront-id": "xxxxxxxxxx"}]'

jobs:
  build-matrix:
    name: build-matrix
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.get-envs.outputs.environments }}
    steps:
      - name: Concat Cloudfront ids
        id: get-envs
        run: |
          JSON=$(echo '[{"environment": "sandbox", "parm1": "aaaaa"}, {"environment": "prod", "param1": "bbbbbb"}]' '${{ inputs.cfids }}' | jq -c -s '[ add | group_by(.environment)[] | select(length > 1) | add ]' )
          echo $JSON
          echo "environments={\"include\": $JSON}"
          echo "environments={\"include\": $JSON}" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT

  check-matrix:
    name: check-matrix
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.environments) }}
    steps:
      - name: Check matrix definition
        run: |
          matrix='${{ needs.build-matrix.outputs.environments }}'
          echo $matrix
          echo $matrix | jq .
