name: Matrix tests

on: 
  workflow_dispatch:
    inputs:
      cfids:
        description: "include array"
        default: '[{"environment": "sandbox", "cloudfront-id": "xxxxxxxxxx"}]'
jobs:

  job2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod, sandbox]
        include: ${{ fromJSON(inputs.cfids) }}
    steps:
      - run: echo ${{ matrix.cloudfront-id }}
