name: Matrix tests

on: 
  workflow_dispatch:
    inputs:
      cfids:
        description: "include array"
        default: '[{"environment": "sandbox", "cloudfront-id": "xxxxxxxxxx"}]'

jobs:
  build-matrix:
    name: build-matrix
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.get-env.outputs.environments }}
    steps:
      - name: Concat Cloudfront ids
        id: get-envs
        run: |
          matrix1='[{"environment": "sandbox", "parm1": "aaaaa"}, {"environment": "prod", "param1": "bbbbbb"}]'
          matrix2='${{ inputs.cfids }}'
          JSON=$(echo $matrix1 $matrix2 | jq -s '[ add | group_by(.environment)[] | select(length > 1) | add ]')
          echo $JSON
          echo "::set-output name=environments::${JSON}"

  check-matrix:
    name: check-matrix
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.environments) }}
    steps:
      - name: Check matrix definition
        run: |
          matrix='${{ needs.build-matrix.outputs.environments }}'
          echo $matrix
          echo $matrix | jq .
