name: Reusable workflow

on:
  workflow_call:
    inputs:
      myinput:
        type: string

jobs:
  example_job:
    name: Print input
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.myinput && format('arn:aws:iam::{0}:role/{1}', secrets.fromJson(inputs.myinput)[0], fromJson(inputs.myinput)[1]) || 'elseinput' }}