name: Secrets tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test env
        env:
          MYENVVAR: ${{ secrets.TEST }}
        run: echo $MYENVVAR

      - name: test with
        uses: ./.github/actions/test
        with:
          myinput: ${{ secrets.TEST }}