name: Test CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1 run"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2 run"
      - run: exit 1

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always()
    steps:
      - run: echo ${{ needs.job1.result }}
      - run: echo ${{ needs.job2.result }}
      - run: echo ${{ fromJSON(needs.*.result) }}
      - run: echo "job3 run"