name: Test CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build run"
      - run: exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "deploy run"

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()
    steps:
      - run: echo ${{ needs.build.result }}
      - run: echo ${{ needs.deploy.result }}
      - run: echo ${{ needs.deploy.result || needs.build.result }}
      - run: echo "notify run"