name: Test CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build run"
      - run: exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "deploy run"

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always() && github.ref_name == 'main'
    steps:
      - name: status
        id: status
        run: |
          BUILD_FAILED=${{ contains(needs.build.result, 'failure') || contains(needs.build.result, 'cancelled') || contains(needs.build.result, 'skipped') }}
          DEPLOY_FAILED=${{ contains(needs.deploy.result, 'failure') || contains(needs.deploy.result, 'cancelled') || contains(needs.deploy.result, 'skipped') }}

          echo "STATUS=succeded" >> $GITHUB_OUTPUT
          if [ $BUILD_FAILED == true ]; then
            echo "STATUS=failed" >> $GITHUB_OUTPUT
          elif [ $DEPLOY_FAILED == true ]; then
            echo "STATUS=terminal" >> $GITHUB_OUTPUT
          fi

      - run: echo ${{ steps.status.outputs.status }}
